= Compiling OPAL
Achim Gsell
:doctype: article
:numbered:

'''

== Introduction

Compiling _OPAL_ can be quite challenging due to all the required
libraries. Even if some libraries are available on the system, this
doesn't mean that they can be used for compiling _OPAL_ due to missing
features. In this document we explain how to compile _OPAL_ from scratch
- including the recommended compiler and all libraries.


== Building OPAL

=== Get the OPAL sources

Clone the OPAL Git repository

----
mkdir -p "${SRC_DIR}/OPAL"
cd "${SRC_DIR}/OPAL"
git clone https://gitlab.psi.ch/OPAL/src.git
----

Select the OPAL branch you want to compile. The current stable branch is `OPAL-2021.1`:

----
cd "${SRC_DIR}/OPAL/src"
git checkout OPAL-2021.1
----

To checkout the (unstable) development branch run:

----
cd "${SRC_DIR}/OPAL/src"
git checkout master
----

To get a list of all available branches, you can run the command

----
git branch -a
----

from inside your clone.


=== Setup OPAL build environment

The environment must be set up as described above for building the dependencies.

=== Configure OPAL

OPAL uses CMake to configure the build process. You can either pass options to `cmake` or you can run the command `ccmake` in the build directory **after** calling `cmake`.

--------------------------------------
mkdir -p "${SRC_DIR}/OPAL/build" && cd "$_"
CC=mpicc CXX=mpicxx cmake \
        --prefix="${PREFIX}" \
        "${SRC_DIR}/OPAL/src"
--------------------------------------

The following table shows the most important options:
[width="80%",cols="3"]
|=======

| `CMAKE_BUILD_TYPE`
| build type can be either `Debug`, `Release`, `RelWithDebInfo` or `MinSizeRel`
|

| `CMAKE_INSTALL_PREFIX`
| prefix for installation
|

| `ENABLE_AMR`
| enable AMR solver
| requires AMReX (release 18.07)

| `ENABLE_AMR_MG_SOLVER`
| enable AMR multigrid solver
| requires trilinos >= 12.x and AMReX (release 18.07) 

| `ENABLE_SAAMG_SOLVER`
| enable SAAMG solver
| requires trilinos >= 12.x and parmetis >= 4.0.3

|=======


=== Compile and install OPAL

----
cd "${SRC_DIR}/OPAL/build"
make -j ${NJOBS}
make install
----

=== Compile OPAL with the SAAMG solver

To compile OPAL with the SAAMG follow the steps in the section "Compile OPAL", but replace the configuration step with:
--------------------------------------
mkdir -p "${SRC_DIR}/OPAL/build"
cd "${SRC_DIR}/OPAL/build"
CC=mpicc CXX=mpicxx cmake \
        --prefix="${PREFIX}" \
        -D ENABLE_SAAMG_SOLVER=TRUE \
        "${SRC_DIR}/OPAL/src"
--------------------------------------
'''