The easiest and recommended solution is to use the **Pmodules** environment available at PSI. How to install and use the Pmodules is explained in the next two sections. The Pmodules are running on 

* Redhat Enterprise Linux 6, 7 and 8 and Clones like Scientific Linux and CentOS
* Ubuntu 18 LTS, 20 LTS, 21 ...
* OpenSUSE leap 15.x

'''

== Check whether Pmodules are available

To check whether Pmodules are available on your system, run `module --version`. The output should look like:

[source=sh]
----
$ module --version

Pmodules 1.0.0rc6 using Tcl Environment Modules 3.2.10
Copyright GNU GPL v2
----

== If not already done, install Pmodules

If Pmodules are not installed on your system, you can either use modules available on AFS or you can install the required modules on your local disk. 

=== Use the modules available on AFS

You (or your system administrator if you don't have `root` access) have to set a symbolic link in the directory `/opt` to the Pmodules installation on AFS:

[source=sh]
----
sudo ln -s /afs/psi.ch/sys/psi.x86_64_slp6 /opt/psi
----

Add the following line to your `.bashrc` or `.bash_profile`:
```
source /opt/psi/config/profile.bash
```

==== Install the required modules on your local disk

1. First you have to choose an installation directory. The modules can be installed anywhere. Around x GB are required for the installation. The following `$DSTDIR` represents the installation directory.
1. In the second step the Pmodules software must be installed with the command:
+
```
/afs/psi.ch/sys/psi.x86_64_slp6/Tools/Pmodules/default/bin/modmanage  init "${DSTDIR}"
```
1. Next we have to setup the symbolic link:
+
```
sudo ln -s "${DSTDIR}" /opt/psi
```
1. Source the configuration file
+
```
source /opt/psi/config/profile.bash
```
Remember to add the same line to your `.bashrc` or `.bash_profile`
1. Now you can install the required modules:
+
```
modmanage install cmake/3.6.3
modmanage install boost/1.62.0 gsl/2.2.1 gtest/1.7.0 OpenBLAS/0.2.19 root/6.08.02 --with=gcc/5.4.0
modmanage install parmetis/4.0.3 --with=gcc/5.4.0 --with=openmpi/1.10.4
modmanage install H5hut/2.0.0rc3 trilinos/12.10.1-1 --with=gcc/5.4.0 --with=openmpi/1.10.4 --with=hdf5/1.8.18
```
1. Optional (only for OPAL versions 2.2 and lower): if you want to compile with DKS (CUDA), you have to install the following modules in addition:
+
```
modmanage install cuda/8.0.44
modmanage install dks/1.1.2 --with=gcc/5.4.0 --with=openmpi/1.10.4
```