= Landing Page of the Object Oriented Parallel Accelerator Library Project

include::attributes.adoc[]
include::stylesheets/Toggle[]

== Introduction

Maybee the best is to look at link:OPAL-References[papers and presentations] to see the potential  and use cases. At the
moment no papers etc. are avaidable for _OPALX_ due to the early stage of the project. However we aim for compatibility
so eben if you are only interetsed in OPALX, looking at the publication of OPAL will give you certainly an idea what to
expect from OPALX. 

Checkout the {link_manual}[manual] for both variants of _OPAL_.

The _OPAL_ mailing list {mail_mailing_list} is used to discuss problems and issues regaring OPAL and OPALX. Subscribe with {link_mailing_list}[**mailing list**].

Please report bugs and feature requests via the {link_mailing_list}[mailing list].
[.feature-opalx]
====
All information about OPALX can be found at {link_manual}[manual].
====

[.feature-opal]
====
_OPAL_ (Object Oriented Parallel Accelerator Library) is a parallel open source tool for charged-particle optics in linear accelerators and rings, including 3D space charge.
Using the MAD language with extensions, _OPAL_ can run on a laptop as well as on the largest high performance computing systems.
_OPAL_ is built from the ground up as a parallel application exemplifying the fact that high performance computing is the third leg of science, complementing theory and experiment.

The _OPAL_ framework makes it easy to add new features in the form of new C++ classes.
_OPAL_ comes in the following flavours:

* _OPAL-cycl_:
  tracks particles with 3D space charge including neighbouring turns in
  cyclotrons and FFAs with time as the independent variable.
* _OPAL-t_:
  models beam lines, linacs, rf-photo injectors and
  complete XFELs.
* _OPAL-map_:
  map tracking (experimental).

The code is managed through the Git distributed version control system. A suite of unit tests have been developed for various parts of _OPAL_, validating each part of the code independently. Unit tests use the google testing framework. System tests validate the overall integration of different elements. Documentation is written in Asciidoc. Tools are available to readily convert Asciidoc into formats such as PDF and HTML for display.

## *Download of Binaries and Clone of Repository*

:link_src_2024-1:  {link_src}/OPAL-2021.1.0/OPAL-2021.1.0
:link_src_2022-1:  {link_src}/OPAL-2022.1.0/OPAL-2022.1.0
:link_src_2021-1:  {link_src}/OPAL-2024.1.0/OPAL-2024.1.0

[%header,width="80%",cols="2,2,2,2,2,2"]
|========
| Version/ +
  Source code 
| Linux binary +
  package
| macOS binary +
  package
| Manual
| Source code +
  documentation
| Release +
  notes

| _OPAL_ development
| n.a.
| n.a.
| {link_manual}[HTML]
| {link_doxydoc}/master[HTML]
| n.a.

| {link_src_2024-1}.tar.xz[_OPAL_ 2024.1.0] ({link_src_2024-1}.tar.xz.md5[md5])
| 
| 
|
| {link_doxydoc}/2024.1[HTML]
| {link_opal_pages}/OPAL-2024.1[Release notes 2024.1]

| {link_src_2022-1}.tar.xz[_OPAL_ 2022.1.0] ({link_src_2022-1}.tar.xz.md5[md5])
| {link_src_2022-1}-1{linux_pkg}            ({link_src_2022-1}-1{linux_md5})
| {link_src_2022-1}-1{macos_pkg}            ({link_src_2022-1}-1{macos_md5}) +
  {link_src_2022-1}-1{macos_arm_pkg}        ({link_src_2022-1}-1{macos_arm_md5})
|
| {link_doxydoc}/2022.1[HTML]
| {link_opal_pages}/OPAL-2022.1[Release notes 2022.1]

| {link_src}/OPAL-2021.1.0.tar.xz[_OPAL_ 2021.1.0] ({link_src}/OPAL-2021.1.0.tar.xz.md5[md5])
| {link_pkg}/OPAL-2021.1.0-1{linux_pkg} ({link_pkg}/OPAL-2021.1.0-1{linux_md5})
| {link_pkg}/OPAL-2021.1.0-1{macos_pkg} ({link_pkg}/OPAL-2021.1.0-1{macos_md5})
|
| {link_doxydoc}/2021.1[HTML]
| {link_opal_pages}/OPAL-2021.1[Release notes 2021.1]

|========

Instead of downloading the source tar-ball you can get the _OPAL_ source via Git. Either clone the whole Git repository (~ 2 GB!) with
[source,sh,subs="attributes"] 
----
git clone {link_OPAL_repo}.git
----

or clone a specific branch/tag with
[source,sh,subs="attributes"] 
----
git clone --single-branch --depth 1  --branch BRANCH_OR_TAG {link_OPAL_repo}.git [DIR]
----

* link:OPAL-binary-package[installing and running a _OPAL_ binary package].
* link:OPAL-binary-package-ChangeLog[ChangeLog of the binary packages].
* link:OPAL-binary-package-old-versions[Deprecated versions].


=== Start with Examples
* link:Examples/Cyclotron.html[Cyclotron]
* link:Examples/RFPhotoInjector.html[AWA RF Photo Injector]
* link:Examples/AWAEEXBeamline.html[AWA EEX Beamline]
* link:Examples/AWADriveLinac.html[AWA Drive Linac]
* link:Examples/RegressionTestExamples.html[Examples from regression tests]
* link:Examples/FFA.html[FFA]
* {link_manual}/{OPAL_VER}/Manual.html#chp.tutorial[Tutorial from Manual]

=== Using _OPAL_ at PSI

* link:Using-OPAL-at-PSI[Using _OPAL_ at PSI]

== Compiling

* link:For-Developers/Supported-OS-and-required-Software-to-build-OPAL[Supported OS and required Software to build _OPAL_]
* link:For-Developers/Setup-build-environment-at-PSI[Setup build environment at PSI]
* link:For-Developers/Compile-required-software[Compile required software (_OPAL_ build recipes)]
* link:For-Developers/Compile-OPAL[Compile _OPAL_]
* link:For-Developers/Compile-OPAL-at-CSCS[Compile _OPAL_ at CSCS]

== For Developers

**Development**

* link:For-Developers/CodingStyle[Coding Style and Conventions]
* link:For-Developers/unit-tests[Building, executing and writing unit tests]
* link:For-Developers/OPAL-Development-Workflow[Development workflow, Git and Gitlab usage]
* link:For-Developers/Release-Procedure[Release Procedure]

**Documentation**

* link:https://amas.pages.psi.ch/opal-live-doc/opal-doxygen/index.html[Doxygen]

**Build-, Unit- and Regression Tests**
The repository for the unit test can be found link:https://github.com/OPALX-project/regression-tests[here].

* link:https://amas.pages.psi.ch/opal-live-doc/opal-regression-test/regressionTests/master/index.html[Regression Tests]
* link:https://amas.pages.psi.ch/opal-live-doc/opal-regression-test/unitTests/master/index.html[Unit Tests]

====
