:TOC:
:numbered:
:blank: pass:[ +]

:OPAL: _OPAL_

:LNK_PKG:  http://amas.web.psi.ch/Downloads/OPAL/package/

:OPAL_VER: 2022.1

:OPAL_VER_LINUX: {OPAL_VER}.0
:OPAL_NVS_LINUX: OPAL-{OPAL_VER_LINUX}
:OPAL_PKG_LINUX: OPAL-{OPAL_VER_LINUX}-1-x86_64-linux.tar.xz
:LNK_PKG_LINUX: {LNK_PKG}{OPAL_PKG_LINUX}

:OPAL_VER_MACOS: {OPAL_VER}.0
:OPAL_NVS_MACOS: OPAL-{OPAL_VER_MACOS}
:OPAL_PKG_MACOS: OPAL-{OPAL_VER_MACOS}-1-x86_64-macos.tar.xz
:LNK_PKG_MACOS: {LNK_PKG}{OPAL_PKG_MACOS}

== Overview 

The newest stable version of OPAL is {OPAL_VER}.

It might be that a binary package of the latest version is not available for all platforms.

'''

## Installation of the OPAL binary distribution

The package can be installed wherever you want. Let's name this directory `$PREFIX`.

### On Linux

1. change your working directory to `$PREFIX`
1. download {LNK_PKG_LINUX}[{OPAL_NVS_LINUX} for Linux]
1. Un-tar the downloaded file:
+
[source,sh,subs="attributes"] 
----
tar xf {OPAL_PKG_LINUX}
----

### On macOS
1. change your working directory to `$PREFIX`
1. download {LNK_PKG_MACOS}[{OPAL_NVS_MACOS} for macOS]
1. Un-tar the downloaded file and remove the quarantine extended attribute:
+
[source,sh,subs="attributes"]
----
tar xf {OPAL_PKG_MACOS}
xattr -dr com.apple.quarantine OPAL-2022.1
----

=== On Windows

You have to use Windows Services for Linux and install the Linux package as documented above.

== Running OPAL

> **Note** MPI is included in the OPAL package. Be sure to use the MPI utilities shipped with the OPAL package!

Source the OPAL shell profile. For the time being only sh-like shells - like BASH, ZSH - are supported.
[source,sh,subs="attributes"]
----
source "$PREFIX/{OPAL_VER}/etc/profile.d/opal.sh"
----
Now you are ready to run OPAL (assuming you have an input file `example.in`):
[source,sh,subs="attributes"]
----
opal example.in
----
or
[source,sh,subs="attributes"]
----
mpirun -np 4 opal example.in
----