= Build OPAL on Linux Systems
Achim Gsell
:doctype: article
:toc:

== Check whether the software requirements are fulfilled on your system
=== 1.1 Requirements

The easiest and recommended solution is to use the **Pmodules** environment available at PSI. How to install and use the Pmodules is explained in the next to sections. If you do not want to use Pmodules you must install the following software packages:


cmake >= 3.0.0
gcc >= 5.4.0
openmpi/1.10.4
boost/1.62.0
hdf5/1.8.18
H5hut/2.0.0rc3
gsl/2.2.1
root/6.08.02
OpenBLAS/0.2.19

gtest >= 1.7.0

parmetis >= 4.0.3
trilinos >= 12.10.1

### 1.2. Check whether Pmodules are available

To check whether Pmodules are available on your system, run `module --version`. The output should look like:

```
$ module --version

Pmodules 0.99.10 using Tcl Environment Modules 3.2.10
Copyright GNU GPL v2
```


### 1.2. If not already done, install Pmodules

If Pmodules are not installed on your system, you (or your system administrator) have to set a symbolic link in the directory `/opt` to the Pmodules installation on AFS:

```
sudo ln -s /afs/psi.ch/sys/psi.x86_64_slp6 /opt/psi
```

Add the following line to your `.bashrc` or `.bash_profile`:
```
source /opt/psi/config/profile.bash
```

**Note**: For the time being Pmodules supports only bash but **not** tcsh.

2. Load the OPAL tool-chain
---------------

Load the OPAL tool-chain for OPAL 1.{5,6}.x
```
module use /afs/psi.ch/project/amas/modulefiles
module load opal-toolschain/1.6
```

and for OPAL 2.x
```
module use /afs/psi.ch/project/amas/modulefiles
module load opal-toolschain/2.0
```

**Note**: For your convenience you might add the line `module use ...` to your `.bashrc` or `.bash_profile`.

3. Get a clone of the OPAL repository
---------------

Choose a directory where you want to store the OPAL sources. Here we use `$HOME/opal`:

```
mkdir $HOME/opal
cd $HOME/opal
git clone git@gitlab.psi.ch:OPAL/src.git
```

4. Select the OPAL branch you want to compile
---------------

Example:
```
cd $HOME/opal/src
git checkout OPAL-1.6
```
or 
```
cd $HOME/opal/src
git checkout master
```

To get a list of all available branches, you can run the command
```
git branch -a
```
from inside your clone.


5. Configure the Build Process
---------------

OPAL uses CMake to configure the build process. You can either pass the option you want to use to `cmake` or you can run the command `ccmake ..` in the build directory **after** calling `cmake ..`:
```
cd "$HOME/opal/src"
mkdir build
cd build
cmake ..    # see available arguments below
ccmake ..  # optional
```

6. Compile OPAL
---------------
```
cd "$HOME/opal/src/build"
make -j 5        # number depends on the number of core on your system
```

