:TOC:
:numbered:
:blank: pass:[ +]

:OPAL: _OPAL_
:OPAL_VER: 2021.1
:OPAL_NAME_VER: OPAL-{OPAL_VER}
:OPAL_PKG: OPAL-2021.1.0-1
:OPAL_PKG_LINUX: {OPAL_PKG}-x86_64-linux.tar.xz
:OPAL_PKG_MACOS: {OPAL_PKG}-x86_64-macos.tar.xz

:LNK_PKG:  http://amas.web.psi.ch/Downloads/OPAL/package/

== Overview 

The newest stable version of OPAL is {OPAL_VER}.

'''

## Installation of the OPAL binary distribution

The package can be installed wherever you want. Let's name this directory `$PREFIX`.

### On Linux

1. change your working directory to `$PREFIX`
1. download {LNK_PKG}{OPAL_PKG_LINUX}[{OPAL_NAME_VER} for Linux]
1. Un-tar the downloaded file:
+
```
tar xf {OPAL_PKG_LINUX}
```

### On macOS
1. change your working directory to `$PREFIX`
1. download http://amas.web.psi.ch/Downloads/OPAL/package/OPAL_PKG}-x86_64-macos.tar.xz[OPAL-2.4.0 for macOS]
1. Un-tar the downloaded file:
+
```
tar xf OPAL-2.4.0-2-x86_64-macos.tar.xz
```

=== On Windows

You have to use Windows Services for Linux and install the Linux package as documented above.

== Running OPAL

> **Note** MPI is included in the OPAL package. Be sure to use the MPI utilities shipped with the OPAL package!

Source the OPAL shell profile. For the time being only sh-like shells - like BASH, ZSH - are supported.
```
source "$PREFIX/OPAL-2.4.0/etc/profile.d/opal.sh"
```
Now you are ready to run OPAL (assuming you have an input file `example.in`):
```
opal example.in
```
or
```
mpirun -np 4 opal example.in
```