= Build OPAL on macOS
Achim Gsell
:doctype: article
:numbered:
:toc:

'''
== Requirements

=== System requirements

* macOS 10.12 or Mac OS X > 10.10 
* Xcode 8 
* Command line utilities for Xcode
* Macports

{nbsp}

=== Required ports
The following ports must be installed:

* cmake
* gcc5
* openmpi-gcc5
* hdf5-18 +gcc5 +cxx +openmpi +threadsafe 
* gsl
* python27 or newer

{nbsp}

=== Software not available as port
The following libraries must be compiled and installed:

* H5hut >= 2.0.0rc3
* boost >= 1.59

{nbsp}

=== Optional requirements
**If you want to run the unit tests, you need `google-test`:**

* gtest >= 1.7.0

{nbsp}

**If you want to compile OPAL with the  SAAMG solver:**

* parmetis from Macports +gcc5 +openmpi
* trilinos >= 12.10.1

{nbsp}

**If you want to compile H5hut with the VTK to H5hut mesh converter, you need:**

* VTK >= 7.1 from Macports

'''
== Compile and install required software

To keep thinks simple, we set and use a couple of environment variables.

{nbsp}

`DOWNLOADS_DIR`::
 is the directory where we store downloaded files. In this instruction we use `${HOME}/Downloads`.

`PREFIX`::
is the common installation prefix for all software we have to compile and install. In the following instructions we use `${HOME}/software`.

`SRC_DIR`::
is the directory where we unpack and compile software. Here we use `${HOME}/src`.
{nbsp}
[listing]
.Set environment variables and create used directories:
--
DOWNLOADS_DIR="${HOME}/Downloads"
PREFIX="${HOME}/software"
SRC_DIR="${HOME}/src"

mkdir -p "${PREFIX}"
mkdir -p "${DOWNLOADS_DIR}"
mkdir -p "${SRC_DIR}"
--
'''
=== Compile and install H5hut

1. **Download H5hut**
+
```
curl -L \
         --output "${DOWNLOADS_DIR}/H5hut-2.0.0rc3.tar.gz" \
         http://amas.web.psi.ch/Downloads/H5hut/H5hut-2.0.0rc3.tar.gz
```
+
1. **Unpack H5hut**
+
```
mkdir -p "${SRC_DIR}/H5hut"
cd "${SRC_DIR}/H5hut"
tar xvf "${DOWNLOADS_DIR}/H5hut-2.0.0rc3.tar.gz"
```
+
1. **Configure H5hut**
+
```
mkdir -p "${SRC_DIR}/H5hut/build"
cd "${SRC_DIR}/H5hut/build"
CC=mpicc CXX=mpicxx "${SRC_DIR}/H5hut/H5hut-2.0.0rc3/configure" \
        --prefix="${PREFIX}" \
        --enable-shared \
        --enable-parallel \
        --with-hdf5=/opt/local/lib/hdf5-18 \
        --with-pic
```
+
1. **Compile and install H5hut**
+
```
cd "${SRC_DIR}/H5hut/build"
make -j4
make install
```

'''
=== Compile and install boost

[NOTE]
.**Remark**
=====================================================================
Boost from Macports cannot be used for several reasons. You have to compile your own version.
=====================================================================

1. **Download boost**
+
```
curl -L \
        --output "${DOWNLOADS_DIR}/boost_1_62_0.tar.gz" \
        https://netcologne.dl.sourceforge.net/project/boost/boost/1.62.0/boost_1_62_0.tar.gz
```
+
1. **Unpack boost**
+
```
mkdir -p "${SRC_DIR}/boost"
cd "${SRC_DIR}/boost"
tar xvf "${DOWNLOADS_DIR}/boost_1_62_0.tar.gz"
```
+
1. **Configure and compile boost:**
+
```
mkdir -p "${SRC_DIR}/boost/build"
cd "${SRC_DIR}/boost/boost_1_62_0"
./bootstrap.sh \
        --prefix="${PREFIX}" \
        --with-libraries=all \
        --with-python-root=/opt/local/
./b2 \
        --build-type=minimal \
        --build-dir="${SRC_DIR}/boost/build" \
        --layout=system \
        --without-mpi \
        variant=release \
        link=shared,static \
        threading=multi \
        stage
```
+
1. **Install boost**
+
```
./b2 \
        --build-type=minimal \
        --build-dir="${SRC_DIR}/boost-build" \
        --layout=system \
        --without-mpi \
        variant=release \
        link=shared,static \
        threading=multi \
        install
```

'''
== Compile OPAL

1. **Get the OPAL sources**
+
Clone the OPAL Git repository
+
```
mkdir -p "${SRC_DIR}/OPAL"
cd "${SRC_DIR}/OPAL"
git clone git@gitlab.psi.ch:OPAL/src.git
```
+
Select the OPAL branch you want to compile. The current stable branch is `OPAL-1.6`:
+
```
cd "${SRC_DIR}/OPAL/src"
git checkout OPAL-1.6
```
+
To checkout the (unstable) development branch run:
+
```
cd "${SRC_DIR}/OPAL/src"
git checkout master
```
+
To get a list of all available branches, you can run the command
+
```
git branch -a
```
+
from inside your clone.
+

1. **Setup OPAL build environment**
+
Before we can configure the build process, we have to setup the environment:
+
--------------------------------------
export HDF5_ROOT="/opt/local/lib/hdf5-18"
export BOOST_ROOT="${PREFIX}"

export C_INCLUDE_PATH="${PREFIX}/include:${HDF5_ROOT}/include"
export CPLUS_INCLUDE_PATH="${C_INCLUDE_PATH}"
export LIBRARY_PATH="${PREFIX}/lib:${HDF5_ROOT}/lib"
--------------------------------------

1. **Configure OPAL**
+
OPAL uses CMake to configure the build process. You can either pass options to `cmake` or you can run the command `ccmake` in the build directory **after** calling `cmake`.
+
--------------------------------------
mkdir -p "${SRC_DIR}/OPAL/build"
cd "${SRC_DIR}/OPAL/build"
CC=mpicc CXX=mpicxx cmake \
        --prefix="${PREFIX}" \
        "${SRC_DIR}/OPAL/src"
--------------------------------------
+
The following table shows the most important options:
+
[width="80%"]
|=======
| `CMAKE_BUILD_TYPE` | build type can be either `Debug`, `Release`, `RelWithDebInfo` or `MinSizeRel` |
| `CMAKE_INSTALL_PREFIX` | prefix for installation |
|=======

1. **Compile and install OPAL**
+
```
cd "${SRC_DIR}/OPAL/build"
make -j 5
make install
```

== Compile OPAL with the SAAMG solver
=== Install ParMETIS
ParMETIS from Macports can be used:
--------------------------------------
sudo port install parmetis +gcc5+openmpi
--------------------------------------

=== Install Trilinos
1. **Download Trilinos**
+
```
curl -L \
         --output "${DOWNLOADS_DIR}/trilinos-12.10.1-Source.tar.bz2" \
         http://trilinos.csbsju.edu/download/files/trilinos-12.10.1-Source.tar.bz2
```
+
1. **Unpack Trilinos**
+
```
mkdir -p "${SRC_DIR}/Trilinos"
cd "${SRC_DIR}/Trilinos"
tar xvf "${DOWNLOADS_DIR}/trilinos-12.10.1-Source.tar.bz2"
```
+
1. **Configure Trilinos**
+
```
mkdir -p "${SRC_DIR}/Trilinos/build"
cd "${SRC_DIR}/Trilinos/build"
CC=mpicc CXX=mpicxx cmake \
        -D CMAKE_INSTALL_PREFIX:PATH="${PREFIX}" \
        -D CMAKE_CXX_FLAGS:STRING="-DMPICH_IGNORE_CXX_SEEK -fPIC" \
        -D CMAKE_C_FLAGS:STRING="-DMPICH_IGNORE_CXX_SEEK -fPIC" \
        -D CMAKE_CXX_STANDARD:STRING="11" \
        -D CMAKE_Fortran_FLAGS:STRING="-fPIC" \
        -D CMAKE_BUILD_TYPE:STRING=Release \
        -D Trilinos_ENABLE_Amesos:BOOL=ON \
        -D Trilinos_ENABLE_Amesos2:BOOL=ON \
        -D Trilinos_ENABLE_AztecOO:BOOL=ON \
        -D Trilinos_ENABLE_Belos:BOOL=ON \
        -D Trilinos_ENABLE_Epetra:BOOL=ON \
        -D Trilinos_ENABLE_EpetraExt:BOOL=ON \
        -D Trilinos_ENABLE_Galeri:BOOL=ON \
        -D Trilinos_ENABLE_Ifpack:BOOL=ON \
        -D Trilinos_ENABLE_Isorropia:BOOL=ON \
        -D Trilinos_ENABLE_ML:BOOL=ON \
        -D Trilinos_ENABLE_NOX:BOOL=ON \
        -D Trilinos_ENABLE_Optika:BOOL=OFF \
        -D Trilinos_ENABLE_Teuchos:BOOL=ON \
        -D Trilinos_ENABLE_Tpetra:BOOL=ON \
        -D Trilinos_ENABLE_TESTS:BOOL=OFF \
        "${SRC_DIR}/Trilinos/trilinos-12.10.1-Source"
```
+
1. **Compile and install Trilinos**
+
```
cd "${SRC_DIR}/Trilinos/build"
make -j4
make install
```

=== Compile OPAL with the SAAMG solver
To compile OPAL with the SAAMG follow the steps in the section "Compile OPAL", but replace the configuration step with:
--------------------------------------
mkdir -p "${SRC_DIR}/OPAL/build"
cd "${SRC_DIR}/OPAL/build"
CC=mpicc CXX=mpicxx cmake \
        --prefix="${PREFIX}" \
        -D ENABLE_SAAMG_SOLVER=TRUE
        "${SRC_DIR}/OPAL/src"
--------------------------------------
'''