= Build OPAL on macOS
Achim Gsell
:doctype: article
:numbered:
:toc:

'''
== Check whether the software requirements are fulfilled on your system
=== Requirements

* macOS 10.12 or Mac OS X > 10.10 
* Xcode 8
* Command line utilities for Xcode
* Macports

{nbsp}

If you *do not* want to use Pmodules you must install the following software packages: 

* cmake >= 3.0.0 from Macports
* gcc >= 5.4.0 from Macports
* openmpi >= 1.10.3 from Macports
* boost >= 1.59 from Macports
* hdf5 1.8.18
* H5hut >= 2.0.0rc3
* gsl >= 2.2 from Macports
* Python >= 2.7 from Macports

{nbsp}

**If you want to run the unit tests, you need `google-test`:** 

* gtest >= 1.7.0 from Macports

{nbsp}

**If you want to compile OPAL with the  SAAMG solver:**

* parmetis >= 4.0.3 from Macports +gcc5 +openmpi
* OpenBLAS >= 0.2.19
* trilinos >= 12.10.1

{nbsp}

**If you want to compile H5root, you need:**

* H5root >= 1.3.3
* root >= 6
* H5hut >= 2.0.0rc3 (serial)

**If you want to compile H5hut with the VTK mesh to H5hut mesh converter, you need:**

* VTK >= 7.1 from Macports

'''
== Compile and install required software

To simplify thinks, we set and use a couple of environment variables.

Set `DOWNLOADS_DIR` to the directory where you want to store downloaded files. Here we use `${HOME}/Downloads`.

Set `PREFIX` to the common installation prefix for all software you have to compile and install. In the following instructions we use `${HOME}/software`. But this can be any location you have write access to.

Set `SRC_DIR` to the directory where you want to unpack and compile software. Here we use `${HOME}/src`.

```
DOWNLOADS_DIR="${HOME}/Downloads"
PREFIX="${HOME}/software"
SRC_DIR="${HOME}/src"
```
Create required directories:
```
mkdir -p "${PREFIX}"
mkdir -p "${DOWNLOADS_DIR}"
mkdir -p "${SRC_DIR}"
```

=== Compile HDF5

Download HDF5:
```
curl -L \
        --output "${DOWNLOADS_DIR}/hdf5-1.8.19.tar.bz2" \
        https://support.hdfgroup.org/ftp/HDF5/current18/src/hdf5-1.8.19.tar.bz2
```
Unpack HDF5:
```
cd "${SRC_DIR}"
tar xvf "${DOWNLOADS_DIR}/hdf5-1.8.19.tar.bz2"
```
Configure HDF5:
```
mkdir -p "${SRC_DIR}/hdf5-build"
cd "${SRC_DIR}/hdf5-build"
CC=mpicc CXX=mpicxx "${SRC_DIR}/hdf5-1.8.19/configure" \
        --prefix="${PREFIX}" \
        --enable-shared \
        --enable-parallel \
        --enable-cxx \
        --enable-unsupported \
        --with-pic
```
Compile and install:
```
cd "${SRC_DIR}/hdf5-build"
make -j4
make install
``

=== Compile H5hut

Download H5hut:
```
curl -L \
        --output "${DOWNLOADS_DIR}/H5hut-2.0.0rc3.tar.gz" \
        http://amas.web.psi.ch/Downloads/H5hut/H5hut-2.0.0rc3.tar.gz
```
Unpack H5hut:
```
cd "${SRC_DIR}"
tar xvf "${DOWNLOADS_DIR}/H5hut-2.0.0rc3.tar.gz"
```
Configure H5hut:
```
mkdir -p "${SRC_DIR}/H5hut-build"
cd "${SRC_DIR}/H5hut-build"
CC=mpicc CXX=mpicxx "${SRC_DIR}/H5hut-2.0.0rc3/configure" \
        --prefix="${PREFIX}" \
        --enable-shared \
        --enable-parallel \
        --with-hdf5="${PREFIX}" \
        --with-pic
```
Compile and install:
```
cd "${SRC_DIR}/H5hut-build"
make -j4
make install
``

=== Compile and install boost

Boost from Macports cannot be used for several reasons. You have to compile your own version.

Download boost:
```
curl -L \
        --output "${DOWNLOADS_DIR}/H5hut-2.0.0rc3.tar.gz" \
        https://netcologne.dl.sourceforge.net/project/boost/boost/1.62.0/boost_1_62_0.tar.gz
        http://amas.web.psi.ch/Downloads/boost_1_62_0.tar.gz
```
Unpack H5hut:
```
cd "${SRC_DIR}"
tar xvf "${DOWNLOADS_DIR}/boost_1_62_0.tar.gz"
```
Configure and compile boost:
```
mkdir -p "${SRC_DIR}/boost-build"
cd "${SRC_DIR}/boost_1_62_0"
./bootstrap.sh \
        --prefix="${PREFIX}" \
        --with-libraries=all \
        --with-python-root=/opt/local/
```
Compile and install
```
cd "${SRC_DIR}/boost_1_62_0"
./b2 \
        --build-type=minimal \
        --build-dir="${SRC_DIR}/boost-build" \
        --layout=system \
        --without-mpi \
        variant=release \
        link=shared,static \
        threading=single \
        stage
./b2 \
        --build-type=minimal \
        --build-dir="${SRC_DIR}/boost-build" \
        --layout=system \
        --without-mpi \
        variant=release \
        link=shared,static \
        threading=single \
        install
```

'''
== Compile OPAL

=== Get the sources:

```
cd "${SRC_DIR}"
git clone git@gitlab.psi.ch:OPAL/src.git OPAL
```

'''
=== Select the OPAL branch you want to compile

Example:

Checkout the newest stable version, which is OPAL 1.6:
```
cd "${SRC_DIR}/OPAL"
git checkout OPAL-1.6
```
or to checkout unstable development version:
```
cd "${SRC_DIR}/OPAL"
git checkout master
```

To get a list of all available branches, you can run the command
```
git branch -a
```
from inside your clone.

'''
=== Configure the Build Process

OPAL uses CMake to configure the build process. You can either pass the option you want to use to `cmake` or you can run the command `ccmake` in the build directory **after** calling `cmake`:
```
export C_INCLUDE_PATH="${PREFIX}/include"
export CPLUS_INCLUDE_PATH="${PREFIX}/include"
export LIBRARY_PATH="${PREFIX}/lib"
export BOOST_ROOT="${PREFIX}"
mkdir -p "${SRC_DIR}/OPAL-build"
cd "${SRC_DIR}/OPAL-build"
cmake  "${SRC_DIR}/OPAL"    # see available arguments below
ccmake "${SRC_DIR}/OPAL"    # optional
```

The following table shows the most important options:
[width="80%"]
|=======
| `CMAKE_BUILD_TYPE` | build type can be either `Debug`, `Release`, `RelWithDebInfo` or `MinSizeRel` |
| `CMAKE_INSTALL_PREFIX` | prefix for installation |
| `ENABLE_AMR_SOLVER` | enable AMR solver | requires BoxLib
| `ENABLE_DKS` | enable DKS | requires Cuda >= 8.0.x and DKS >= 1.1.1
| `ENABLE_SAAMG_SOLVER` | enable SAAMG solver | requires trilinos >= 12.x and parmetis >= 4.0.3
|=======

*Example:*
```
cmake -DCMAKE_BUILD_TYPE=Release -DENABLE_DKS=TRUE ..
```

'''
== Compile OPAL
```
cd "$HOME/opal/src/build"
make -j 5        # number depends on the number of cores on your system
```
