= Build OPAL on Piz Daint at CSCS
Matthias Frey
:doctype: article
:numbered:
:toc:

'''
== Account

'''
=== Creation
First you need a proper CSCS account. In order to do that click on http://www.cscs.ch/user_lab/applying_for_accounts/index.html[this link].

'''
=== Login
One has first to access http://www.cscs.ch/computers/ela/index.html[Ela] before being able to login to http://www.cscs.ch/computers/piz_daint/index.html[Piz Daint].

```
$ ssh username@ela.cscs.ch
> ssh daint

```

'''
== Modules
The hybrid architecture of Piz Daint allows to run on GPUs and CPUs. Therefore, it provides two modules in order to set up the
environment properly:

```
> module load daint-gpu
> module load daint-mc
```
This instruction only shows the installation of OPAL for the multicore architecture (i.e. the module ```daint-mc```).

'''
=== Load compiler
```
> module load daint-mc
> module switch PrgEnv-cray/6.0.4 PrgEnv-gnu/6.0.4
> module switch gcc/5.3.0 gcc/7.1.0
```

'''
=== Building H5hut

There's no H5hut module available on Piz Daint. You can install it using subsequent steps:
```
> cd $HOME/git
> mkdir H5hut
> cd H5hut
> git clone git@gitlab.psi.ch:H5hut/src.git
> cd src
> ./autogen.sh
> module load daint-mc 
> module switch PrgEnv-cray/6.0.4 PrgEnv-gnu/6.0.4
> module switch gcc/5.3.0 gcc/7.1.0
> module load CMake/3.9.1 
> module load cray-hdf5-parallel/1.10.0
> module load GSL/2.4-CrayGNU-17.08
```

The environment variables for the GSL library are not set, you have to do it manually:
```
> export GSL_HOME= /apps/dom/UES/jenkins/6.0.UP04/mc/easybuild/software/GSL/2.4-CrayGNU-17.08/
> export GSL_DIR=$GSL_HOME
> export GSL_PREFIX=$GSL_PREFIX
> export GSL_INCLUDE_DIR=$GSL_HOME/include
> export GSL_LIBRARY_DIR=$GSL_HOME/lib
```

Compile it with:
```
> ./autogen.sh
> CXX=CC CC=cc FC=ftn ./configure --prefix=$HOME/git/H5hut/build --enable-parallel --with-hdf5=$HDF5_ROOT
> make
> make install
```

Finally, we set some evironment variables:
```
> export H5HUT_HOME=$HOME/git/H5hut/build
> export H5HUT_PREFIX=$H5HUT_HOME
> export H5HUT_DIR=$H5HUT_HOME
> export H5HUT_INCLUDE_DIR=$H5HUT_HOME/include
> export H5HUT_LIBRARY_DIR=$H5HUT_HOME/lib
```
**Note**: For your convenience you might add above lines to your `.bashrc`.

'''
=== Building Boost
```
> cd $HOME
> wget https://sourceforge.net/projects/boost/files/boost/1.62.0/boost_1_62_0.tar.gz
> tar -xf boost_1_62_0.tar.gz
> module load daint-mc
> module switch PrgEnv-cray/6.0.4 PrgEnv-gnu/6.0.4
> module switch gcc/5.3.0 gcc/7.1.0
> module load CMake/3.9.1 
> ./bootstrap.sh --prefix=$HOME/boost_1_62_0/build
> ./b2 --build-type=minimal --layout=system --without-mpi variant=release link=shared,static threading=multi install
```
Finally, we set some evironment variables:
```
> export BOOST_HOME=$HOME/boost_1_62_0/build/
> export BOOST_DIR=$BOOST_HOME
> export BOOST_PREFIX=$BOOST_HOME
> export BOOST_INCLUDE_DIR=$BOOST_HOME/include
> export BOOST_LIBRARY_DIR=$BOOST_HOME/lib
```
**Note**: For your convenience you might add above lines to your `.bashrc`.

'''
=== Building OPAL
Assuming you have Boost and H5hut installed, you're now able to build OPAL. See in section https://gitlab.psi.ch/OPAL/src/wikis/For%20Developers/Compile-OPAL-on-RHEL6#user-content-building-opal[Building OPAL] if you do not yet have the OPAL source code.

Set up the environment:
```
> module load daint-mc
> module switch PrgEnv-cray/6.0.4 PrgEnv-gnu/6.0.4
> module load GSL/2.4-CrayGNU-17.08
> module load CMake/3.9.1
> module load cray-hdf5-parallel/1.10.0
> module switch gcc/5.3.0 gcc/7.1.0

> export H5HUT_HOME=$HOME/git/H5hut/build
> export H5HUT_PREFIX=$H5HUT_HOME
> export H5HUT_DIR=$H5HUT_HOME
> export H5HUT_INCLUDE_DIR=$H5HUT_HOME/include
> export H5HUT_LIBRARY_DIR=$H5HUT_HOME/lib

> export BOOST_HOME=$HOME/boost_1_62_0/build/
> export BOOST_DIR=$BOOST_HOME
> export BOOST_PREFIX=$BOOST_HOME
> export BOOST_INCLUDE_DIR=$BOOST_HOME/include
> export BOOST_LIBRARY_DIR=$BOOST_HOME/lib

> export GSL_HOME= /apps/dom/UES/jenkins/6.0.UP04/mc/easybuild/software/GSL/2.4-CrayGNU-17.08/
> export GSL_DIR=$GSL_HOME
> export GSL_PREFIX=$GSL_PREFIX
> export GSL_INCLUDE_DIR=$GSL_HOME/include
> export GSL_LIBRARY_DIR=$GSL_HOME/lib

> export MPI_HOME=$MPICH_DIR
> export MPI_PREFIX=$MPI_HOME
> export MPI_INCLUDE_DIR=$MPI_HOME/include
> export MPI_LIBRARY_DIR=$MPI_HOME/lib
```
Assuming you have the source code in `$HOME/opal/src`, do:
```
> cd $HOME/opal
> mkdir build
> cd build
> CXX=CC CC=cc cmake -DUSE_H5HUT2=1 ../src
> make
```

You might add the executable path to the environment variable:
```
> export OPAL_EXE_PATH=$HOME/opal/build/src/
> export PATH=$OPAL_EXE_PATH:$PATH
```
Make sure you use the right directory. You can check if it worked with
```
> which opal
```
or
```
> whereis opal
```

'''
== Modification of ~/.bashrc
It's convenient to add a helper function to your `~/.bashrc` in order to make life easier:

```
load_opal_gcc710() {
    module load daint-mc
    module switch PrgEnv-cray/6.0.4 PrgEnv-gnu/6.0.4                                                          
    module load GSL/2.4-CrayGNU-17.08
    module load CMake/3.9.1
    module load cray-hdf5-parallel/1.10.0
    module switch gcc/5.3.0 gcc/7.1.0

    export H5HUT_HOME=$HOME/git/H5hut/build
    export H5HUT_PREFIX=$H5HUT_HOME
    export H5HUT_DIR=$H5HUT_HOME
    export H5HUT_INCLUDE_DIR=$H5HUT_HOME/include
    export H5HUT_LIBRARY_DIR=$H5HUT_HOME/lib

    export BOOST_HOME=$HOME/boost_1_62_0/build/
    export BOOST_DIR=$BOOST_HOME
    export BOOST_PREFIX=$BOOST_HOME
    export BOOST_INCLUDE_DIR=$BOOST_HOME/include
    export BOOST_LIBRARY_DIR=$BOOST_HOME/lib

    export GSL_HOME=/apps/dom/UES/jenkins/6.0.UP04/mc/easybuild/software/GSL/2.4-CrayGNU-17.08/
    
    export GSL_DIR=$GSL_HOME
    export GSL_PREFIX=$GSL_PREFIX
    export GSL_INCLUDE_DIR=$GSL_HOME/include
    export GSL_LIBRARY_DIR=$GSL_HOME/lib
    
    export MPI_HOME=$MPICH_DIR
    export MPI_PREFIX=$MPI_HOME
    export MPI_INCLUDE_DIR=$MPI_HOME/include
    export MPI_LIBRARY_DIR=$MPI_HOME/lib
    
    export OPAL_EXE_PATH=$HOME/opal/build/src/
    export PATH=$OPAL_EXE_PATH:$PATH
}
```

At the next login (or by just doing `source ~/.bashrc`) you can load everything by executing
```
> load_opal_gcc710
```
