= Compiling OPAL
Achim Gsell
:doctype: article
:numbered:
:toc:
:toc-placement: preamble
:toclevels: 2

// Need some preamble to get TOC:
{empty}

'''

== Introduction

Compiling OPAL can be quite challenging due to all the required
libraries. Even if some libraries are available on the system, this
doesn't mean that they can be used for compiling OPAL due to missing
features. In this document we explain how to compile OPAL from scratch
- including the recommended compiler and all libraries. 

== Requirements

=== System requirements

* Operating system
  * Linux system with development tools installed (Windows service for
    Linux has been reported to work with these instructions) 
  * Mac with macos > 10.12 and Xcode installed 
* Python 2.7
* zlib >= 1.2.11

{nbsp}

=== Required software

The list below shows the required software, the minimal version and
the recommended version in parenthesis.

[width="100%",options="header"]
|=======
| **Name**  | **minimum Version** | **recommended Version** | **Notes**

| GNU Multiple Precision Arithmetic Library (GMP) | 6.0.0 | 6.1.2
| required to compile GCC

| GNU MPFR Library | 3.1.0 | 4.0.1 | required to compile GCC

| GNU MPC Library | 1.0.0 | 1.1.0 | required to compile GCC

| GNU Compiler Collection | 5.3.0 | 7.3.0 | Do not try to build GCC < 7.1.0 on macOS!

| cmake | 3.0.0 | 3.11.4 |
1. CMake shipped with RHEL 7 and older cannot be used! +
2. CMake version 3.11.4 (and newer) requires C&#43;&#43; 11. +
3. GCC 4.8.x shipped with RHEL7 cannot be used! +
4. Please note that version 3.6.3 has some known issues with hdf5. +
5. Version 3.11.4 requires a C++ compiler supporting C++11.

| Open MPI | 1.10.2 | 3.1.2 | as alternative MPICH can be used

| hdf5 | 1.8.18 | 1.10.3 | A parallel version is required.

| GNU Scientific Library | 2.4 | 2.5 |

| H5hut | 2.0.0rc3 | 2.0.0rc4 | A parallel version is required.

| boost | 1.59 | 1.68.0 
| The following boost libraries are required: `chrono`, `filesystem`,
 `iostreams`, `regex`, `serialization`, `system`

| google-test | 1.7.0 | 1.7.0 | optional: Required to run the unit-tests

| ParMETIS | 4.0.0 | 4.0.3
| optional: required for OPAL compiled with SAAMG solver.

| OpenBLAS | 0.2.9 | 0.2.20
| optional: required for OPAL compiled with SAAMG solver.

| trilinos | 12.10.1 | 12.10.1
| optional: required for OPAL compiled with SAAMG solver.

| VTK | 7.1 | 8.0.0
| optional: required of you want to compile H5hut with the VTK to H5hut mesh converter.
|=======

Before compiling everything yourself, you might want to try the versions available on your system. Check the requirements before trying. The following software usually works without problems: cmake >= 3.0.0, gcc >= 5.3.0, gsl >= 2.4, boost >= 1.59, MPI.

'''

== Setting up the environment

To keep thinks simple, we set and use a couple of environment variables.

`PREFIX`::
Installation prefix for all software we have to compile and install. In the following instructions we use `${HOME}/OPAL`.

`DOWNLOADS_DIR`::
 This is the directory where we store downloaded files. In this instruction we use `${PREFIX}/Downloads`.

`SRC_DIR`::
This is the directory where we unpack and compile software. Here we use `${PREFIX}/src`.

`njobs`::
number of parallel `make` jobs. The number should be less or equal the number of core on your system plus one. If your system has more then 8 cores, setting `njobs`to eight is quite reasonable.

[listing]
.Set environment variables and create used directories:
--
PREFIX="${HOME}/OPAL"
DOWNLOADS_DIR="${PREFIX}/Downloads"
SRC_DIR="${PREFIX}/src"

PATH="${PREFIX}/bin:${PATH}"

if [[ -z "${C_INCLUDE_PATH}" ]]; then
      C_INCLUDE_PATH="${PREFIX}/include"
else
      C_INCLUDE_PATH="${PREFIX}/include:${C_INCLUDE_PATH}"
fi

if [[ -z "${CPLUS_INCLUDE_PATH}" ]]; then
      CPLUS_INCLUDE_PATH="${PREFIX}/include"
else
      CPLUS_INCLUDE_PATH="${PREFIX}/include:${CPLUS_INCLUDE_PATH}"
fi

if [[ -z "${LIBRARY_PATH}" ]]; then
      LIBRARY_PATH="${PREFIX}/lib:${PREFIX}/lib64"
else
      LIBRARY_PATH="${PREFIX}/lib:${PREFIX}/lib64:${LIBRARY_PATH}"
fi

if [[ -z "${LD_LIBRARY_PATH}" ]]; then
      LD_LIBRARY_PATH="${PREFIX}/lib:${PREFIX}/lib64"
else
      LD_LIBRARY_PATH="${PREFIX}/lib:${PREFIX}/lib64:${LD_LIBRARY_PATH}"
fi

export C_INCLUDE_PATH
export CPLUS_INCLUDE_PATH
export LIBRARY_PATH
export LD_LIBRARY_PATH

NJOBS=4

mkdir -p "${PREFIX}"
mkdir -p "${DOWNLOADS_DIR}"
mkdir -p "${SRC_DIR}"
--
'''

== Compile and install required software

=== Build everything from scratch

The recipes should work on Linux and macOS. Tested with:

* macOS 10.13 and Xcode 10 (ongoing)

Build the software in this order:

1. link:Recipes/gmp[GMP]
1. link:Recipes/mpfr[MPFR]
1. link:Recipes/mpc[MPC]
1. link:Recipes/gcc[GCC]
1. link:Recipes/cmake[CMake]
1. link:Recipes/openmpi[open-mpi]
1. link:Recipes/hdf5[HDF5]
1. link:Recipes/gsl[GSL]
1. link:Recipes/h5hut[H5hut]
1. link:Recipes/boost[Boost]
1. link:Recipes/parmetis[ParMETIS]
1. link:Recipes/openblas[OpenBLAS]
1. link:Recipes/trilinos[Trilinos]

'''

== Building OPAL

1. **Get the OPAL sources**
+
Clone the OPAL Git repository
+
```
mkdir -p "${SRC_DIR}/OPAL"
cd "${SRC_DIR}/OPAL"
git clone git@gitlab.psi.ch:OPAL/src.git
```
+
Select the OPAL branch you want to compile. The current stable branch is `OPAL-1.6`:
+
```
cd "${SRC_DIR}/OPAL/src"
git checkout OPAL-1.6
```
+
To checkout the (unstable) development branch run:
+
```
cd "${SRC_DIR}/OPAL/src"
git checkout master
```
+
To get a list of all available branches, you can run the command
+
```
git branch -a
```
+
from inside your clone.
+

1. **Setup OPAL build environment**
+
The environment must be set up as described above for building the dependencies.
+
1. **Configure OPAL**
+
OPAL uses CMake to configure the build process. You can either pass options to `cmake` or you can run the command `ccmake` in the build directory **after** calling `cmake`.
+
--------------------------------------
mkdir -p "${SRC_DIR}/OPAL/build" && cd "$_"
CC=mpicc CXX=mpicxx cmake \
        --prefix="${PREFIX}" \
        "${SRC_DIR}/OPAL/src"
--------------------------------------
+
The following table shows the most important options:
+
[width="80%"]
|=======
| `CMAKE_BUILD_TYPE` | build type can be either `Debug`, `Release`, `RelWithDebInfo` or `MinSizeRel` |
| `CMAKE_INSTALL_PREFIX` | prefix for installation |
|=======

1. **Compile and install OPAL**
+
```
cd "${SRC_DIR}/OPAL/build"
make -j ${NJOBS}
make install
```

== Compile OPAL with the SAAMG solver

To compile OPAL with the SAAMG follow the steps in the section "Compile OPAL", but replace the configuration step with:
--------------------------------------
mkdir -p "${SRC_DIR}/OPAL/build"
cd "${SRC_DIR}/OPAL/build"
CC=mpicc CXX=mpicxx cmake \
        --prefix="${PREFIX}" \
        -D ENABLE_SAAMG_SOLVER=TRUE \
        "${SRC_DIR}/OPAL/src"
--------------------------------------
'''