= Build OPAL on Linux at PSI
Achim Gsell
:doctype: article
:numbered:
:toc:

'''

== Introduction

> The easiest and recommended solution is to use the **Pmodules** environment available at PSI. Please link:Pmodules[read this wiki-page] if you are not using a PSI  Linux distribution or you do not know whether the Pmodules are installed on your system.

> If you *do not* want to use Pmodules, please follow the instruction for link:Compile-OPAL-on-RHEL6[building OPAL from scratch].

'''

== Load the OPAL tool-chain

Load the OPAL tool-chain for OPAL 1.{5,6}.x
```
module use /afs/psi.ch/project/amas/modulefiles
module load opal-toolschain/1.6
```

and for OPAL 2.x
```
module use /afs/psi.ch/project/amas/modulefiles
module use unstable
module load opal-toolschain/2.0
```

> **Note**: For your convenience you might add these lines to your `.bashrc` or `.bash_profile`.

Optional:
```
module load cuda/8.0.44
module load dks/1.1.2
```

'''
== Get a clone of the OPAL repository

Choose a directory where you want to store the OPAL sources. Here we use `$HOME/opal`:

```
mkdir $HOME/opal
cd $HOME/opal
git clone git@gitlab.psi.ch:OPAL/src.git
```

'''
== Select the OPAL branch you want to compile

Example:
```
cd $HOME/opal/src
git checkout OPAL-1.6
```
or 
```
cd $HOME/opal/src
git checkout master
```

To get a list of all available branches, you can run the command
```
git branch -a
```
from inside your clone.

'''
== Configure the Build Process

OPAL uses CMake to configure the build process. You can either pass the option you want to use to `cmake` or you can run the command `ccmake ..` in the build directory **after** calling `cmake ..`:
```
cd "$HOME/opal/src"
mkdir build
cd build
cmake ..    # see available arguments below
ccmake ..  # optional
```

The following table shows the most important options:
[width="80%"]
|=======
| `CMAKE_BUILD_TYPE` | build type can be either `Debug`, `Release`, `RelWithDebInfo` or `MinSizeRel` |
| `CMAKE_INSTALL_PREFIX` | prefix for installation |
| `ENABLE_AMR_SOLVER` | enable AMR solver | requires BoxLib
| `ENABLE_DKS` | enable DKS | requires Cuda >= 8.0.x and DKS >= 1.1.1
| `ENABLE_SAAMG_SOLVER` | enable SAAMG solver | requires trilinos >= 12.x and parmetis >= 4.0.3
|=======

*Example:*
```
cmake -DCMAKE_BUILD_TYPE=Release -DENABLE_DKS=TRUE ..
```

'''
== Compile OPAL
```
cd "$HOME/opal/src/build"
make -j 5        # number depends on the number of cores on your system
```
