= Compiling OPAL from scratch
Achim Gsell
:doctype: article
:numbered:
:toc:
:toc-placement: preamble
:toclevels: 2

// Need some preamble to get TOC:
{empty}

'''

== Introduction

Compiling OPAL can be quite challenging due to all the required
libraries. Even if some libraries are available on the system, this
doesn't mean that they can be used for compiling OPAL due to missing
features. In this document we explain how to compile OPAL from scratch
- including the recommended compiler and all libraries. 

== Requirements

=== System requirements

* Operating system
  * Linux system with development tools installed (Windows service for
    Linux has been reported to work with these instructions) 
  * Mac with macos > 10.12 and Xcode installed 
* Python 2.7
* zlib >= 1.2.11

{nbsp}

=== Required software

The following software must be available on your system. You may try
with version available for your system. Sometimes useful version are
available from some software repositories. On macOS you can try the
versions available via Macports or Homebrew.

The list below shows the required software, the minimal version and
the recommended version in parenthesis.

* cmake >= 3 (3.11.4) Please note version 3.6.3 has some known issues
  with hdf5
* GNU Multiple Precision Arithmetic Library (GMP) >= 6 (6.1.2)
* GNU MPFR Library >= 3.1 (4.0.1)
* GNU MPC Library >= 1 (1.1.0)
* GNU Compiler Collection 7.3.0
* Open MPI >= 1.10.2 (3.1.2)
* hdf5 >= 1.8.18 (1.10.3) 
* GNU Scientific Library >= 2.4 (2.5)
* H5hut >= 2.0.0rc3 (2.0.0rc4)
* boost >= 1.59 (1.68.0)

{nbsp}

=== Optional requirements
**If you want to run the unit tests, you need `google-test`:**

* gtest >= 1.7.0 (1.7.0)

{nbsp}

**If you want to compile OPAL with the  SAAMG solver:**

* ParMETIS >= 4 (4.0.3)
* OpenBLAS >= 0.2.9 (0.2.20)
* trilinos >= 12.10.1 (12.10.1)

{nbsp}

**If you want to compile H5hut with the VTK to H5hut mesh converter, you need:**

* VTK >= 7.1 (8.0.0)

'''
== Setting up the environment

To keep thinks simple, we set and use a couple of environment variables.

{nbsp}

`DOWNLOADS_DIR`::
 is the directory where we store downloaded files. In this instruction we use `${HOME}/Downloads`.

`PREFIX`::
is the common installation prefix for all software we have to compile and install. In the following instructions we use `${HOME}/software`.

`SRC_DIR`::
is the directory where we unpack and compile software. Here we use `${HOME}/src`.
`njobs`::
number of parallel `make` jobs. The number should be less or equal the number of core on your system plus one. If your system has more then 8 cores, setting `njobs`to eight is quite reasonable.
{nbsp}
[listing]
.Set environment variables and create used directories:
--
DOWNLOADS_DIR="${HOME}/Downloads"
PREFIX="${HOME}/software"
SRC_DIR="${HOME}/src"

PATH="${PREFIX}/bin:${PATH}"

if [[ -z "${C_INCLUDE_PATH}" ]]; then
      C_INCLUDE_PATH="${PREFIX}/include"
else
      C_INCLUDE_PATH="${PREFIX}/include:${C_INCLUDE_PATH}"
fi

if [[ -z "${CPLUS_INCLUDE_PATH}" ]]; then
      CPLUS_INCLUDE_PATH="${PREFIX}/include"
else
      CPLUS_INCLUDE_PATH="${PREFIX}/include:${CPLUS_INCLUDE_PATH}"
fi

if [[ -z "${LIBRARY_PATH}" ]]; then
      LIBRARY_PATH="${PREFIX}/lib:${PREFIX}/lib64"
else
      LIBRARY_PATH="${PREFIX}/lib:${PREFIX}/lib64:${LIBRARY_PATH}"
fi

if [[ -z "${LD_LIBRARY_PATH}" ]]; then
      LD_LIBRARY_PATH="${PREFIX}/lib:${PREFIX}/lib64"
else
      LD_LIBRARY_PATH="${PREFIX}/lib:${PREFIX}/lib64:${LD_LIBRARY_PATH}"
fi

export C_INCLUDE_PATH
export CPLUS_INCLUDE_PATH
export LIBRARY_PATH
export LD_LIBRARY_PATH

NJOBS=4

mkdir -p "${PREFIX}"
mkdir -p "${DOWNLOADS_DIR}"
mkdir -p "${SRC_DIR}"
--
'''

== Compile and install required software

Build the software in this order:

1. link:Recipes/cmake[CMake]
1. link:Recipes/gmp[GMP]
1. link:Recipes/mpfr[MPFR]
1. link:Recipes/mpc[MPC]
1. link:Recipes/gcc[GCC5]
1. link:Recipes/openmpi[open-mpi]
1. link:Recipes/hdf5[HDF5]
1. link:Recipes/gsl[GSL]
1. link:Recipes/h5hut[H5hut]
1. link:Recipes/boost[Boost]
1. link:Recipes/parmetis[ParMETIS]
1. link:Recipes/openblas[OpenBLAS]
1. link:Recipes/trilinos[Trilinos]

'''

== Building OPAL

1. **Get the OPAL sources**
+
Clone the OPAL Git repository
+
```
mkdir -p "${SRC_DIR}/OPAL"
cd "${SRC_DIR}/OPAL"
git clone git@gitlab.psi.ch:OPAL/src.git
```
+
Select the OPAL branch you want to compile. The current stable branch is `OPAL-1.6`:
+
```
cd "${SRC_DIR}/OPAL/src"
git checkout OPAL-1.6
```
+
To checkout the (unstable) development branch run:
+
```
cd "${SRC_DIR}/OPAL/src"
git checkout master
```
+
To get a list of all available branches, you can run the command
+
```
git branch -a
```
+
from inside your clone.
+

1. **Setup OPAL build environment**
+
The environment must be set up as described above for building the dependencies.
+
1. **Configure OPAL**
+
OPAL uses CMake to configure the build process. You can either pass options to `cmake` or you can run the command `ccmake` in the build directory **after** calling `cmake`.
+
--------------------------------------
mkdir -p "${SRC_DIR}/OPAL/build" && cd "$_"
CC=mpicc CXX=mpicxx cmake \
        --prefix="${PREFIX}" \
        "${SRC_DIR}/OPAL/src"
--------------------------------------
+
The following table shows the most important options:
+
[width="80%"]
|=======
| `CMAKE_BUILD_TYPE` | build type can be either `Debug`, `Release`, `RelWithDebInfo` or `MinSizeRel` |
| `CMAKE_INSTALL_PREFIX` | prefix for installation |
|=======

1. **Compile and install OPAL**
+
```
cd "${SRC_DIR}/OPAL/build"
make -j ${NJOBS}
make install
```

== Compile OPAL with the SAAMG solver

To compile OPAL with the SAAMG follow the steps in the section "Compile OPAL", but replace the configuration step with:
--------------------------------------
mkdir -p "${SRC_DIR}/OPAL/build"
cd "${SRC_DIR}/OPAL/build"
CC=mpicc CXX=mpicxx cmake \
        --prefix="${PREFIX}" \
        -D ENABLE_SAAMG_SOLVER=TRUE \
        "${SRC_DIR}/OPAL/src"
--------------------------------------
'''
