= Build OPAL on RHEL6
Achim Gsell
:doctype: article
:numbered:
:toc:
:toc-placement: preamble
:toclevels: 2

// Need some preamble to get TOC:
{empty}

'''
== Requirements

=== System requirements

* Redhat Enterprise Linux 6 or clones like CentOS, ScientificLinux
* C-compiler, autotools, make etc.
* Python 2.7

{nbsp}

=== Required software

Unfortunately most of the software to build OPAL is not available as RPM from the standard repositories including EPEL. The following packages must be build and installed, in parenthesis the recommended version we are using in our tool-chain:

* cmake >= 3 (3.6.3)
* GNU Multiple Precision Arithmetic Library (GMP) >= 6 (6.1.2)
* GNU MPFR Library >= 3.1 (3.1.5)
* GNU MPC Library >= 1 (1.0.3)
* GNU Compiler Collection 5.4.0
* Open MPI >= 1.10.2 (1.10.4)
* zlib >= 1.2.11
* hdf5 >= 1.8.18 (1.8.18) 
* GNU Scientific Library >= 2.4 (2.4)
* H5hut >= 2.0.0rc3 (2.0.0rc3)
* boost >= 1.59 (1.62.0)

{nbsp}

=== Optional requirements
**If you want to run the unit tests, you need `google-test`:**

* gtest >= 1.7.0 (1.7.0)

{nbsp}

**If you want to compile OPAL with the  SAAMG solver:**

* ParMETIS >= 4 (4.0.3)
* OpenBLAS >= 0.2.9 (0.2.20)
* trilinos >= 12.10.1 (12.10.1)

{nbsp}

**If you want to compile H5hut with the VTK to H5hut mesh converter, you need:**

* VTK >= 7.1 (8.0.0)

'''
== Compile and install required software

To keep thinks simple, we set and use a couple of environment variables.

{nbsp}

`DOWNLOADS_DIR`::
 is the directory where we store downloaded files. In this instruction we use `${HOME}/Downloads`.

`PREFIX`::
is the common installation prefix for all software we have to compile and install. In the following instructions we use `${HOME}/software`.

`SRC_DIR`::
is the directory where we unpack and compile software. Here we use `${HOME}/src`.
`njobs`::
number of parallel `make` jobs. The number should be less or equal the number of core on your system plus one. If your system has more then 8 cores, setting `njobs`to eight is quite reasonable.
{nbsp}
[listing]
.Set environment variables and create used directories:
--
DOWNLOADS_DIR="${HOME}/Downloads"
PREFIX="${HOME}/software"
SRC_DIR="${HOME}/src"

PATH="${PREFIX}/bin:${PATH}"

if [[ -z "${C_INCLUDE_PATH}" ]]; then
      C_INCLUDE_PATH="${PREFIX}/include"
else
      C_INCLUDE_PATH="${PREFIX}/include:${C_INCLUDE_PATH}"
fi

if [[ -z "${CPLUS_INCLUDE_PATH}" ]]; then
      CPLUS_INCLUDE_PATH="${PREFIX}/include"
else
      CPLUS_INCLUDE_PATH="${PREFIX}/include:${CPLUS_INCLUDE_PATH}"
fi

if [[ -z "${LIBRARY_PATH}" ]]; then
      LIBRARY_PATH="${PREFIX}/lib:${PREFIX}/lib64"
else
      LIBRARY_PATH="${PREFIX}/lib:${PREFIX}/lib64:${LIBRARY_PATH}"
fi

if [[ -z "${LD_LIBRARY_PATH}" ]]; then
      LD_LIBRARY_PATH="${PREFIX}/lib:${PREFIX}/lib64"
else
      LD_LIBRARY_PATH="${PREFIX}/lib:${PREFIX}/lib64:${LD_LIBRARY_PATH}"
fi

export C_INCLUDE_PATH
export CPLUS_INCLUDE_PATH
export LIBRARY_PATH
export LD_LIBRARY_PATH

NJOBS=4

mkdir -p "${PREFIX}"
mkdir -p "${DOWNLOADS_DIR}"
mkdir -p "${SRC_DIR}"
--
'''

== Compile and install required software

Build the software in this order:

1. link:Recipes/cmake[CMake]
1. link:Recipes/gmp[GMP]
'''
=== Building MPFR
1. **Set package and version**
+
```
P=mpfr
V=3.1.5
```
+
1. **Download MPFR**
+
```
curl -L \
	--output "${DOWNLOADS_DIR}/$P-$V.tar.gz" \
	"http://www.mpfr.org/$P-$V/$P-$V.tar.gz"
```
+
1. **Unpack MPFR**
+
```
mkdir -p "${SRC_DIR}/$P" && cd "$_"
tar xvf "${DOWNLOADS_DIR}/$P-$V.tar.gz"
```
+
1. **Configure MPFR**
+
```
mkdir -p "${SRC_DIR}/$P/build" && cd "$_"
"${SRC_DIR}/$P/$P-$V/configure" \
		--prefix="${PREFIX}" \
		--with-gmp="${PREFIX}" \
		--disable-shared
```
+
1. **Compile and install MPFR**
```
make -j ${NJOBS}
make install
```

'''
=== Building MPC
1. **Set package and version**
+
```
P=mpc
V=1.0.3
```
+
1. **Download MPC**
+
```
curl -L \
	--output "${DOWNLOADS_DIR}/$P-$V.tar.gz" \
	"ftp://ftp.gnu.org/gnu/$P/$P-$V.tar.gz"
```
+
1. **Unpack MPC**
+
```
mkdir -p "${SRC_DIR}/$P" && cd "$_"
tar xvf "${DOWNLOADS_DIR}/$P-$V.tar.gz"
```
+
1. **Configure MPC**
+
```
mkdir -p "${SRC_DIR}/$P/build" && cd "$_"
"${SRC_DIR}/$P/$P-$V/configure" \
		--prefix="${PREFIX}" \
		--with-gmp="${PREFIX}" \
		--with-mpfr="${PREFIX}" \
		--disable-shared
```
+
1. **Compile and install MPC**
+
```
make -j ${NJOBS}
make install
```

'''
=== Building GCC 5.4
1. **Set package and version**
+
```
P=gcc
V=5.4.0
```
+
1. **Download GCC**
+
```
curl -L \
	--output "${DOWNLOADS_DIR}/$P-$V.tar.bz2" \
	"https://ftp.gnu.org/gnu/$P/$P-$V/$P-$V.tar.bz2"
```
+
1. **Unpack GCC**
+
```
mkdir -p "${SRC_DIR}/$P" && cd "$_"
tar xvf "${DOWNLOADS_DIR}/$P-$V.tar.bz2"
```
+
1. **Configure GCC**
+
```
mkdir -p "${SRC_DIR}/$P/build" && cd "$_"
"${SRC_DIR}/$P/$P-$V/configure" \
			--prefix="${PREFIX}" \
			--with-gmp="${PREFIX}" \
			--with-mpfr="${PREFIX}" \
			--with-mpc="${PREFIX}" \
			--enable-languages=c,c++,objc,obj-c++,lto,fortran \
			--enable-lto \
			--disable-multilib \
			--with-build-config=bootstrap-debug
```
+
1. **Compile and install GCC**
```
make -j ${NJOBS}
make install
```

'''
=== Building Open MPI
1. **Set package and version**
+
```
P=openmpi
V=1.10.4
```
+
1. **Download openmpi**
+
```
curl -L \
	--output "${DOWNLOADS_DIR}/$P-$V.tar.bz2" \
	"http://www.open-mpi.org/software/ompi/v${V%.*}/downloads/$P-$V.tar.bz2"
```
+
1. **Unpack openmpi**
+
```
mkdir -p "${SRC_DIR}/$P" && cd "$_"
tar xvf "${DOWNLOADS_DIR}/$P-$V.tar.bz2"
```
+
1. **Configure openmpi**
+
```
mkdir -p "${SRC_DIR}/$P/build" && cd "$_"
"${SRC_DIR}/$P/$P-$V/configure" \
		--prefix="${PREFIX}" \
		--enable-mpi-cxx \
		--enable-mpi-cxx-seek \
		--enable-mpi-profile \
		--enable-orterun-prefix-by-default \
		--enable-shared \
		--enable-smp-locks \
		--with-sge=yes \
		--with-slurm=yes
```
+
1. **Compile and install openmpi**
```
make -j ${NJOBS}
make install
```

'''
=== Building hdf5
1. **Set package and version**
+
```
P=hdf5
V=1.8.18
```
+
1. **Download hdf5**
+
```
curl -L \
	--output "${DOWNLOADS_DIR}/$P-$V.tar.bz2" \
	"https://support.hdfgroup.org/ftp/HDF5/releases/$P-${V%.*}/$P-$V/src/$P-$V.tar.bz2"
```
+
1. **Unpack hdf5**
+
```
mkdir -p "${SRC_DIR}/$P" && cd "$_"
tar xvf "${DOWNLOADS_DIR}/$P-$V.tar.bz2"
```
+
1. **Configure hdf5**
+
```
mkdir -p "${SRC_DIR}/$P/build" && cd "$_"
CC=mpicc CXX=mpicxx FC=mpifort "${SRC_DIR}/$P/$P-$V/configure" \
        --prefix="${PREFIX}" \
        --enable-shared \
        --enable-parallel \
        --enable-cxx \
        --enable-fortran \
        --enable-unsupported \
        --with-pic
```
+
1. **Compile and install hdf5**
+
```
make -j ${NJOBS}
make install
```

'''
=== Building the GNU Scientific Library
1. **Set package and version**
+
```
P=gsl
V=2.4
```
+
1. **Download GSL**
+
```
curl -L \
	--output "${DOWNLOADS_DIR}/$P-$V.tar.gz" \
	"ftp://ftp.gnu.org/gnu/$P/$P-$V.tar.gz"
```
+
1. **Unpack GSL**
+
```
mkdir -p "${SRC_DIR}/$P" && cd "$_"
tar xvf "${DOWNLOADS_DIR}/$P-$V.tar.gz"
```
+
1. **Configure GSL**
+
```
mkdir -p "${SRC_DIR}/$P/build" && cd "$_"
"${SRC_DIR}/$P/$P-$V/configure" \
		--prefix="${PREFIX}" \
		--disable-shared
```
+
1. **Compile and install GSL**
```
make -j ${NJOBS}
make install
```

'''
=== Building H5hut
1. **Set package and version**
+
```
P=H5hut
V=2.0.0rc3
```
+
1. **Download H5hut**
+
```
curl -L \
         --output "${DOWNLOADS_DIR}/$P-$V.tar.gz" \
         http://amas.web.psi.ch/Downloads/$P/$P-$V.tar.gz
```
+
1. **Unpack H5hut**
+
```
mkdir -p "${SRC_DIR}/$P" && cd "$_"
tar xvf "${DOWNLOADS_DIR}/$P-$V.tar.gz"
```
+
1. **Configure H5hut**
+
```
mkdir -p "${SRC_DIR}/$P/build" && cd "$_"
CC=mpicc CXX=mpicxx "${SRC_DIR}/$P/$P-$V/configure" \
        --prefix="${PREFIX}" \
        --enable-shared \
        --enable-parallel \
        --with-pic
```
+
1. **Compile and install H5hut**
+
```
make -j ${NJOBS}
make install
```

'''
=== Building Boost
1. **Set package and version**
+
```
P=boost
V=1_62_0
```
+
1. **Download boost**
+
```
curl -L \
        --output "${DOWNLOADS_DIR}/${P}_$V.tar.gz" \
        "https://netcologne.dl.sourceforge.net/project/$P/$P/${V//_/.}/${P}_$V.tar.gz"
```
+
1. **Unpack boost**
+
```
mkdir -p "${SRC_DIR}/$P" && cd "$_"
tar xvf "${DOWNLOADS_DIR}/${P}_$V.tar.gz"
```
+
1. **Configure boost**
+
```
mkdir -p "${SRC_DIR}/$P/build"
cd "${SRC_DIR}/$P/${P}_$V"
./bootstrap.sh \
                --prefix="${PREFIX}" \
                --with-libraries=all
```
+
1. **Compile & install boost**
+
```
./b2 \
        --build-type=minimal \
        --build-dir=""${SRC_DIR}/$P/build"" \
        --layout=system \
        --without-mpi \
        variant=release \
        link=shared,static \
        threading=multi \
        stage
./b2 \
        --build-type=minimal \
        --build-dir=""${SRC_DIR}/$P/build"" \
        --layout=system \
        --without-mpi \
        variant=release \
        link=shared,static \
        threading=multi \
        install
```

'''
=== Building ParMETIS

ParMETIS is required only, if you want to compile OPAL with the SAAMG solver.
It is a dependency of Trilinos.

1. **Set package and version**
+
```
P=parmetis
V=4.0.3
```
+
1. **Download ParMETIS**
+
```
curl -L \
        --output "${DOWNLOADS_DIR}/$P-$V.tar.gz" \
        "http://glaros.dtc.umn.edu/gkhome/fetch/sw/$P/$P-$V.tar.gz"
```
+
1. **Unpack ParMETIS**
+
```
mkdir -p "${SRC_DIR}/$P" && cd "$_"
tar xvf "${DOWNLOADS_DIR}/$P-$V.tar.gz"
```
+
1. **Configure ParMETIS**
+
```
mkdir -p "${SRC_DIR}/$P/build" && cd "$_"
CC=mpicc CXX=mpicxx cmake \
	 -D CMAKE_INSTALL_PREFIX:PATH="${PREFIX}" \
	 -D METIS_PATH="${SRC_DIR}/$P/$P-$V/metis" \
	 -D GKLIB_PATH="${SRC_DIR}/$P/$P-$V/metis/GKlib" \
	 "${SRC_DIR}/$P/$P-$V"
```
+
1. **Compile and install ParMetis**
+
```
make -j ${NJOBS}
make install
install --mode 0644 libmetis/libmetis.a "${PREFIX}/lib"
install --mode 0644 "${SRC_DIR}/$P/$P-$V/metis/include/metis.h" "${PREFIX}/include"
```

'''
=== Building OpenBLAS

OpenBLAS is required only, if you want to compile OPAL with the SAAMG solver.
It is a dependency of Trilinos.

1. **Set package and version**
+
```
P=OpenBLAS
V=0.2.20
```
+
1. **Download OpenBLAS**
+
```
curl -L \
        --output "${DOWNLOADS_DIR}/$P-$V.tar.gz" \
        "http://github.com/xianyi/$P/archive/v$V.tar.gz"
```
+
1. **Unpack OpenBLAS**
+
```
mkdir -p "${SRC_DIR}/$P" && cd "$_"
tar xvf "${DOWNLOADS_DIR}/$P-$V.tar.gz"
```
+
1. **Configure OpenBLAS**
+
No need to configure something. There is experimental CMake support,
but seems to be still broken.
+
1. **Compile and install OpenBLAS**
+
We compile with target `CORE2`. There might be issues with other targets like `HASWELL`.
Anyway you can try with other targets. For auto-detection just run `make`. Note: We run `make` in the source directory.
+
```
mkdir -p "${SRC_DIR}/$P/$P-$V" && cd "$_"
make TARGET=CORE2
make TARGET=CORE2 PREFIX="${PREFIX}" install
```

'''
=== Building Trilinos

Trilinos is required only, if you want to compile OPAL with the SAAMG solver.

1. **Set package and version**
+
```
P=trilinos
V=12.10.1
```
+
1. **Download Trilinos**
+
```
curl -L \
         --output "${DOWNLOADS_DIR}/$P-$V-Source.tar.bz2" \
         http://trilinos.csbsju.edu/download/files/$P-$V-Source.tar.bz2
```
+
1. **Unpack Trilinos**
+
```
mkdir -p "${SRC_DIR}/$P" && cd "$_"
tar xvf "${DOWNLOADS_DIR}/$P-$V-Source.tar.bz2"
```
+
1. **Configure Trilinos**
+
```
mkdir -p "${SRC_DIR}/$P/build" && cd "$_"
CC=mpicc CXX=mpicxx cmake \
        -D CMAKE_INSTALL_PREFIX:PATH="${PREFIX}" \
        -D CMAKE_CXX_FLAGS:STRING="-DMPICH_IGNORE_CXX_SEEK -fPIC" \
        -D CMAKE_C_FLAGS:STRING="-DMPICH_IGNORE_CXX_SEEK -fPIC" \
        -D CMAKE_CXX_STANDARD:STRING="11" \
        -D CMAKE_Fortran_FLAGS:STRING="-fPIC" \
        -D CMAKE_BUILD_TYPE:STRING=Release \
        -D TPL_ENABLE_DLlib:BOOL=OFF \
        -D TPL_ENABLE_QT:BOOL=OFF \
        -D TPL_ENABLE_MPI:BOOL=ON \
        -D TPL_ENABLE_BLAS:BOOL=ON \
        -D TPL_ENABLE_LAPACK:BOOL=ON \
        -D TPL_ENABLE_METIS:BOOL=ON \
        -D TPL_ENABLE_ParMETIS:BOOL=ON \
        -D BLAS_LIBRARY_DIRS:PATH="${PREFIX}/lib" \
        -D BLAS_INCLUDE_DIRS:PATH="${PREFIX}/include" \
        -D BLAS_LIBRARY_NAMES:STRING="openblas" \
        -D LAPACK_LIBRARY_DIRS:PATH="${PREFIX}/lib" \
        -D LAPACK_INCLUDE_DIRS:PATH="${PREFIX}/include" \
        -D LAPACK_LIBRARY_NAMES:STRING="openblas" \
        -D TPL_METIS_INCLUDE_DIRS:PATH="${PREFIX}/include" \
        -D TPL_METIS_LIBRARIES:STRING="${PREFIX}/lib/libmetis.a" \
        -D TPL_ParMETIS_INCLUDE_DIRS:PATH="${PREFIX}/include" \
        -D TPL_ParMETIS_LIBRARIES:STRING="${PREFIX}/lib/libparmetis.a" \
        -D Trilinos_ENABLE_Amesos:BOOL=ON \
        -D Trilinos_ENABLE_Amesos2:BOOL=ON \
        -D Trilinos_ENABLE_AztecOO:BOOL=ON \
        -D Trilinos_ENABLE_Belos:BOOL=ON \
        -D Trilinos_ENABLE_Epetra:BOOL=ON \
        -D Trilinos_ENABLE_EpetraExt:BOOL=ON \
        -D Trilinos_ENABLE_Galeri:BOOL=ON \
        -D Trilinos_ENABLE_Ifpack:BOOL=ON \
        -D Trilinos_ENABLE_Isorropia:BOOL=ON \
        -D Trilinos_ENABLE_ML:BOOL=ON \
        -D Trilinos_ENABLE_NOX:BOOL=ON \
        -D Trilinos_ENABLE_Optika:BOOL=OFF \
        -D Trilinos_ENABLE_Teuchos:BOOL=ON \
        -D Trilinos_ENABLE_Tpetra:BOOL=ON \
        -D Trilinos_ENABLE_TESTS:BOOL=OFF \
        "${SRC_DIR}/$P/$P-$V-Source"
```
+
1. **Compile and install Trilinos**
+
```
make -j ${NJOBS}
make install
```

'''
== Building OPAL

1. **Get the OPAL sources**
+
Clone the OPAL Git repository
+
```
mkdir -p "${SRC_DIR}/OPAL"
cd "${SRC_DIR}/OPAL"
git clone git@gitlab.psi.ch:OPAL/src.git
```
+
Select the OPAL branch you want to compile. The current stable branch is `OPAL-1.6`:
+
```
cd "${SRC_DIR}/OPAL/src"
git checkout OPAL-1.6
```
+
To checkout the (unstable) development branch run:
+
```
cd "${SRC_DIR}/OPAL/src"
git checkout master
```
+
To get a list of all available branches, you can run the command
+
```
git branch -a
```
+
from inside your clone.
+

1. **Setup OPAL build environment**
+
The environment must be set up as described above for building the dependencies.
+
1. **Configure OPAL**
+
OPAL uses CMake to configure the build process. You can either pass options to `cmake` or you can run the command `ccmake` in the build directory **after** calling `cmake`.
+
--------------------------------------
mkdir -p "${SRC_DIR}/OPAL/build" && cd "$_"
CC=mpicc CXX=mpicxx cmake \
        --prefix="${PREFIX}" \
        "${SRC_DIR}/OPAL/src"
--------------------------------------
+
The following table shows the most important options:
+
[width="80%"]
|=======
| `CMAKE_BUILD_TYPE` | build type can be either `Debug`, `Release`, `RelWithDebInfo` or `MinSizeRel` |
| `CMAKE_INSTALL_PREFIX` | prefix for installation |
|=======

1. **Compile and install OPAL**
+
```
cd "${SRC_DIR}/OPAL/build"
make -j ${NJOBS}
make install
```

== Compile OPAL with the SAAMG solver

To compile OPAL with the SAAMG follow the steps in the section "Compile OPAL", but replace the configuration step with:
--------------------------------------
mkdir -p "${SRC_DIR}/OPAL/build"
cd "${SRC_DIR}/OPAL/build"
CC=mpicc CXX=mpicxx cmake \
        --prefix="${PREFIX}" \
        -D ENABLE_SAAMG_SOLVER=TRUE \
        "${SRC_DIR}/OPAL/src"
--------------------------------------
'''
