= Build OPAL on Linux at PSI
Achim Gsell
:doctype: article
:numbered:
:toc:

'''

== Introduction

> The easiest and recommended solution is to use the **Pmodules** environment available at PSI. Please link:Pmodules[read this wiki-page] if you are not using a PSI  Linux distribution or you do not know whether the Pmodules are installed on your system.

>
If you *do not* want to use Pmodules, please follow the instruction for link:Compile-OPAL-on-RHEL6[building OPAL from scratch].

== Check whether the software requirements are fulfilled on your system
=== Requirements

The easiest and recommended solution is to use the **Pmodules** environment available at PSI. How to install and use the Pmodules is explained in the next two sections. The Pmodules are running on 

* Redhat Enterprise Linux 6 and 7 and Clones like Scientific Linux and Centor
* Ubuntu 14 LTS and 16 LTS
* OpenSUSE should work but is not tested


'''

=== Check whether Pmodules are available

To check whether Pmodules are available on your system, run `module --version`. The output should look like:

```
$ module --version

Pmodules 0.99.10 using Tcl Environment Modules 3.2.10
Copyright GNU GPL v2
```

{nbsp}

=== If not already done, install Pmodules

If Pmodules are not installed on your system, you can either use modules available on AFS or you can install the required modules on your local disk. 

**Note**: For the time being Pmodules supports only bash but **not** tcsh.

==== Use the modules on AFS

You (or your system administrator if you don't have `root` access) have to set a symbolic link in the directory `/opt` to the Pmodules installation on AFS:

```
sudo ln -s /afs/psi.ch/sys/psi.x86_64_slp6 /opt/psi
```

Add the following line to your `.bashrc` or `.bash_profile`:
```
source /opt/psi/config/profile.bash
```

==== Install the required modules on your local disk

1. First you have to choose an installation directory. The modules can be installed anywhere. Around x GB are required for the installation. The following `$DSTDIR` represents the installation directory.
1. In the second step the Pmodules software must be installed with the command:
+
```
/afs/psi.ch/sys/psi.x86_64_slp6/Tools/Pmodules/default/bin/modmanage  init "${DSTDIR}"
```
1. Next we have to setup the symbolic link:
+
```
sudo ln -s "${DSTDIR}" /opt/psi
```
1. Source the configuration file
+
```
source /opt/psi/config/profile.bash
```
Remember to add the same line to your `.bashrc` or `.bash_profile`
1. Now you can install the required modules:
+
```
modmanage install cmake/3.6.3
modmanage install boost/1.62.0 gsl/2.2.1 gtest/1.7.0 OpenBLAS/0.2.19 root/6.08.02 --with=gcc/5.4.0
modmanage install parmetis/4.0.3 --with=gcc/5.4.0 --with=openmpi/1.10.4
modmanage install H5hut/2.0.0rc3 trilinos/12.10.1-1 --with=gcc/5.4.0 --with=openmpi/1.10.4 --with=hdf5/1.8.18
```
1. Optional: if you want to compile with DKS (CUDA), you have to install the following modules in addition:
+
```
modmanage install cuda/8.0.44
modmanage install dks/1.1.2 --with=gcc/5.4.0 --with=openmpi/1.10.4
```

'''
== Load the OPAL tool-chain

Load the OPAL tool-chain for OPAL 1.{5,6}.x
```
module use /afs/psi.ch/project/amas/modulefiles
module load opal-toolschain/1.6
```

and for OPAL 2.x
```
module use /afs/psi.ch/project/amas/modulefiles
module use unstable
module load opal-toolschain/2.0
```

**Note**: For your convenience you might add these lines to your `.bashrc` or `.bash_profile`.

Optional:
```
module load cuda/8.0.44
module load dks/1.1.2
```

'''
== Get a clone of the OPAL repository

Choose a directory where you want to store the OPAL sources. Here we use `$HOME/opal`:

```
mkdir $HOME/opal
cd $HOME/opal
git clone git@gitlab.psi.ch:OPAL/src.git
```

'''
== Select the OPAL branch you want to compile

Example:
```
cd $HOME/opal/src
git checkout OPAL-1.6
```
or 
```
cd $HOME/opal/src
git checkout master
```

To get a list of all available branches, you can run the command
```
git branch -a
```
from inside your clone.

'''
== Configure the Build Process

OPAL uses CMake to configure the build process. You can either pass the option you want to use to `cmake` or you can run the command `ccmake ..` in the build directory **after** calling `cmake ..`:
```
cd "$HOME/opal/src"
mkdir build
cd build
cmake ..    # see available arguments below
ccmake ..  # optional
```

The following table shows the most important options:
[width="80%"]
|=======
| `CMAKE_BUILD_TYPE` | build type can be either `Debug`, `Release`, `RelWithDebInfo` or `MinSizeRel` |
| `CMAKE_INSTALL_PREFIX` | prefix for installation |
| `ENABLE_AMR_SOLVER` | enable AMR solver | requires BoxLib
| `ENABLE_DKS` | enable DKS | requires Cuda >= 8.0.x and DKS >= 1.1.1
| `ENABLE_SAAMG_SOLVER` | enable SAAMG solver | requires trilinos >= 12.x and parmetis >= 4.0.3
|=======

*Example:*
```
cmake -DCMAKE_BUILD_TYPE=Release -DENABLE_DKS=TRUE ..
```

'''
== Compile OPAL
```
cd "$HOME/opal/src/build"
make -j 5        # number depends on the number of cores on your system
```
