== December 10, 2019

[discrete]
==== Agenda

. OPAL Christmas release https://gitlab.psi.ch/OPAL/src/issues?milestone_title=OPAL-2.2.0[2.2.0]
. OPAL Paper
. link:opal-developer-&-user-retreat/slac-2020[OPAL Retreat SLAC 2020]
. E-meeting frequency
. OPAL Manual Workflow
. AOB

[discrete]
==== Minutes

. DKS will be in 2.4. All open issues for the milestones 2.2 will be closed or moved to 2.4 by Monday.
. If Suzy is not answering by Friday I will divide the work of english checking among Nicole, Daniel and
Chris. THANKS A LOT!
. OPAL Retreat SLAC 2020 (March 30 to April 3)

_I recommend booking a placeholder soon (if you want a traditional hotel).
Closest towns are Redwood City, Palo Alto, Menlo Park, and Sunnyvale.
Here's a list of Sunnyvale options our admin has used in the past:_

* Wild Palms Hotel Sunnyvale
* Cherry orchard Inn Sunnyvale
* Courtyard by Marriott Hotel Cupertino
* AC Hotel by Marriott Sunnyvale
* Cupertino Inn

_Public transportation is available by bus (leaving from campus), on 30 minute intervals during the day (~7am to ~8pm):
https://transportation.stanford.edu/marguerite_

Due to problems with the original date we evaluating the following *alternative: Feb 17 to 22*. By Christmas we should have a decision.

. Nicole will make a Doodle for a monthly meeting plan. We start one hour earlier.
. The Manual workflow as it is was not debated. A great plus is the ability to do small changes with the
_edit button_ hence without going to the entire workflow.
. None
