:stem: latexmath
:sectnums:
:toc: macro
:toclevels: 3

link:home[Back to Main Page]

toc::[]

[[chp:sample]]
Sampler
--------
This is a modification of the https://gitlab.psi.ch/OPAL/src/wikis/Manual/optimiser[optimiser]. Instead of performing a multi-objective optimisation, it creates samples of the design variables and runs those simulations. This feature can be used for example as training / validation of neural networks or uncertainty quantification (UQ).

[[sample-commands]]
OPAL Commands
~~~~~~~~~~~~~
It uses almost the same syntax as the optimiser.

Basic Syntax
^^^^^^^^^^^^
One needs to define the design variables and their sampling method. The syntax for
design variables is described in the section https://gitlab.psi.ch/OPAL/src/wikis/Manual/optimiser[DVAR Command].

SAMPLE Command
^^^^^^^^^^^^^^
[#samplecommandattributes]
.Attributes for the command SAMPLE.
[cols="<1,<5",options="header",]
|=======================================================================
|Attribute |Description
| INPUT |  Path to input file.
| OUTPUT |  Name used in output file generation.
| OUTDIR |  Name of directory used to store generation output files.
| DVARS |  List of design variables to be used.
| SAMPLINGS | List of sample methods to be used.
| N | Number of samples to run.
| NUM_MASTERS |  Number of master nodes (currently only 1 master supported).
| NUM_COWORKERS |  Number processors per worker.
| SIMTMPDIR |  Directory where simulations are run.
| TEMPLATEDIR |  Directory where templates are stored.
| FIELDMAPDIR |  Directory where field maps are stored.
|=======================================================================

SAMPLING Command
^^^^^^^^^^^^^^^^
[#samplingcommandattributes]
.Attributes for the command SAMPLING.
[cols="<1,<5",options="header",]
|=======================================================================
|Attribute |Description
| VARIABLE | Name of the design variable.
| TYPE |  Sampling method (see next section).
| SEED |  Seed for random sampling (default: 42).
| FNAME | File to read the samples from.
|=======================================================================

Available Sampling Methods
^^^^^^^^^^^^^^^^^^^^^^^^^^
[#samplemethods]
.Available sampling methods.
[cols="<1,<5",options="header",]
|=======================================================================
| Method |Description
| FROMFILE | The samples are provided by a file. A column represents the
             values of a design variable. The first line is the header reading
             the variable name. Not all variables need to be provided in the file.
             This allows also reading variables from different files.
| SEQUENCE | Generates an equidistant sequence taking the lower and upper
             bound of the design variable command. 
| UNIFORM_INT| Uniform random sampling of integers. It takes the lower and
               upper bound of the design variable command.
| UNIFORM_REAL |  Like UNIFORM_INT but for floats.
|=======================================================================

Example Input File
^^^^^^^^^^^^^^^^^^

....
OPTION, INFO=TRUE;

// Design variables
nstep:  DVAR, VARIABLE="nstep", LOWERBOUND=10,     UPPERBOUND=40;
MX:     DVAR, VARIABLE="MX",    LOWERBOUND=16,      UPPERBOUND=32;


SM1: SAMPLING, VARIABLE="nstep", TYPE="FROMFILE", FNAME="fname.dat";
SM2: SAMPLING, VARIABLE="MX", TYPE="UNIFORM_INT", SEED=122;


SAMPLE,
    N               = 10,
    DVARS           = {nstep, MX},
    SAMPLINGS       = {SM1, SM2},
    INPUT           = "Ring.tmpl",
    OUTPUT          = "RingOpt",
    OUTDIR          = "RingOpt",
    SIMTMPDIR       = "tmp",
    TEMPLATEDIR     = "template",
    FIELDMAPDIR     = "Fieldmaps",
    NUM_MASTERS     = 1,
    NUM_COWORKERS   = 1;
QUIT;
....

