name: Publish Website and Quarto Manual

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read
  pages: write       # to deploy to Pages
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout Manual
        uses: actions/checkout@v4
        with:
          repository: OPALX-project/Manual
          ref: master
          path: Manual-new-src

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install Asciidoctor
        run: |
          gem install asciidoctor

      - name: Build AsciiDoc
        run: |
          bash ./build-local.sh

      - name: Build Quarto Manual
        run: |
          quarto render ./Manual-new-src/quarto --to html
          mkdir -p build/Manual-new
          cp -R ./Manual-new-src/quarto/docs-quarto/. ./build/Manual-new/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
